#Jenkins install

---
- hosts: CIserver
  become: yes
  
  tasks:
    - name: ensure the jenkins apt repository gpg key is installed
      become: yes
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present

    - name: ensure the repository is configured
      become: yes
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Update apt packages
      become: yes
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: INSTALL aptitude
      become: yes
      apt:
        name: aptitude
        state: present

    - name: INSTALL openjdk-11-jdk
      become: yes
      apt:
        name: openjdk-11-jdk
        update_cache: yes

    - name: INSTALL jenkins
      become: yes
      apt:
        name: jenkins
        state: latest
        update_cache: yes

    - name: daemon-reload to pick up config changes
      become: yes
      ansible.builtin.systemd:
        daemon_reload: yes
 
    - name: jenkins daemon systmectl enable
      become: yes
      ansible.builtin.systemd:
        name: jenkins
        enabled: yes

    - name: Start jenkins
      become: yes
      ansible.builtin.systemd:
        name: jenkins
        state: started
